FROM public.ecr.aws/lambda/python:3.12

# Install build tools
RUN dnf install -y vim make gcc gzip tar zip

COPY entrypoint.layer.sh ./

# Fix permissions
RUN chmod +x entrypoint.layer.sh

ENTRYPOINT ["./entrypoint.layer.sh"]
